services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
    sebk_small_user_provider:
        class: Sebk\SmallUserBundle\Security\UserProvider
    Sebk\SmallUserBundle\Security\UserProvider:
        alias: sebk_small_user_provider
    Sebk\SmallUserBundle\Security\UserVoter:
        tags: [ security.voter ]
    Sebk\SmallUserBundle\Command\:
        resource: '../../Command/*'
        tags: [ console.command ]
    Sebk\SmallUserBundle\Controller\:
        resource: '../../Controller/*'
        tags: [ controller.service_arguments ]