services:
    _defaults:
        public: true
    sebk_small_users_provider:
        class: Sebk\SmallUserBundle\Security\UserProvider
        arguments: ["@sebk_small_orm_dao", "@sebk_small_orm_validator", "@security.encoder_factory"]
    Sebk\SmallUserBundle\Command\CreateUserCommand:
        public: true
        tags: [console.command]
    Sebk\SmallUserBundle\Command\ChangePasswordCommand:
        public: true
        tags: [console.command]
    Sebk\SmallUserBundle\Command\AddRoleCommand:
        public: true
        tags: [console.command]
    Sebk\SmallUserBundle\Command\RemoveRoleCommand:
        public: true
        tags: [console.command]
    Sebk\SmallUserBundle\Command\EnableUserCommand:
        public: true
        tags: [console.command]
    Sebk\SmallUserBundle\Command\DisableUserCommand:
        public: true
        tags: [console.command]